-- Insert admin user
-- IMPORTANT: Set ADMIN_EMAIL and ADMIN_PASSWORD_HASH as environment variables.
-- Generate a bcrypt hash for your password using: https://bcrypt-generator.com/
-- Then run this SQL in Supabase SQL Editor with your real values.

-- Example (replace placeholders with your actual values):
-- INSERT INTO users (name, email, password, role, password_set)
-- VALUES (
--   'Admin',
--   'your-admin-email@example.com',
--   '$2a$12$YOUR_BCRYPT_HASH_HERE',
--   'admin',
--   true
-- ) ON CONFLICT (email) DO NOTHING;
